### ISSUE TITLE
Distribute through PyPI

### ISSUE THREAD

**Issue by cthoyt** [jose-manuel/npfc#2]
Installation instruction (https://github.com/jose-manuel/npfc#instructions) are quite complicated. It would be nice if it could simply be pip installed with `pip install npfc`

**Comment by jose-manuel** [comment]
Hi, sorry for the very long delay. I made the package installable via pip.  

However an error is thrown during the deduplication if pytables is installed via pip, but not if it is installed via conda (as it is in my dev env). Both packages have the same version though (3.6.1). I will try with an older version at some point.

I updated the installation instruction accordingly.
